### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by lukasbystricky** [chapkachapka/owen-johnson_stover-at-yale#1]
- [x] Run semanticate. I believe the change in chapter-23 should be accepted. (I'm running the latest toolkit, so if nothing happens for you it's ok)
- [ ] There's also a lint error in chapter-5, again maybe only with the latest tools
- [x] I think the phrase "p's and q's" falls under rule [8.2.8.3](https://standardebooks.org/manual/1.7.4/8-typography#8.2.8.3) and so doesn't need to be tagged or italicized.
- [x] For the table in chapter-12 the summation bar can just be the top border of the total cell. You can set this with CSS targeting the second td of the footer.

**Comment by chapkachapka** [comment]
I don't see anything in lint; I've fixed the other three issues. If you let me know what the error message is I can take a look.

**Comment by lukasbystricky** [comment]
This is what lint says:
t-074 │ Manual Review │ chapter-5.xhtml │ Extended sound using hyphen-minus - instead of non-breaking hyphen ‑.                                                                                         │ <i>brek-e-kek-kex</i>       

 If you think that's an error you can try and convert those to non-breaking hyphens (like this one ‑), otherwise you can add an ignore.

**Comment by chapkachapka** [comment]
I've added the ignore file; in my judgment this is "hip-hip-hooray" not "No-o-o!".

Lint now gives me an "usused ignore entry" warning but I assume you won't see this on your end; let me know if you need any changes to the ignore file.

**Comment by lukasbystricky** [comment]
Yeah looks good on my end. I'll pass it off to Alex.
